### PR TITLE
Web Utils

### PR DESCRIPTION
**Pull request by seailz**
[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette 

 
- [x] I have checked the PRs for upcoming features/bug fixes. 
- [x] I have read the [contributing guidelines][contributing]. 

 
### Changes 
- [ ] Internal code 
- [x] Library interface (affecting end-user code) 
- [x] Documentation 
- [ ] Other: \_____  

 

Closes Issue: NaN 

## Description 
Web utils, a way to interact with HTTP requests with ease.

# Documentation

## Sending a GET request
When sending a GET request, the method will return a JSONObject. Here's how to do that:

```java
JSONObject obj = WebUtils.sendGetRequest("your_url_here");
```

## Sending a POST request

```java
WebUtils.sendPostRequest("your_url_here", "your_data_here");
```

### CODE REVIEW

**Comment by seailz** [comment]
> What exactly would this be used for?

sending easier get and post requests, for example, retrieving something from the hypixel api

**Comment by joeecodes** [comment]
Ah ok

**Comment by NegativeDev** [comment]
What use will this have for plugins? I can see it being useful for Mods but not so much for plugins as you rarely interact with rest apis in plugin development with the exception being licensing systems

**Comment by NegativeDev** [comment]
> What use will this have for plugins? I can see it being useful for Mods but not so much for plugins as you rarely interact with rest apis in plugin development with the exception being licensing systems

with that I don't really see this being practical enough to include in the api

**Pull request closed without merging**
