### PR TITLE
Fixed the package

### PR DESCRIPTION
**Pull request by IoyoCode**
Updated the package for BungeeManager.java so it is now in the correct place.

### CODE REVIEW

**Comment by NegativeKB** [comment]
Wrong base branch.

**Review by joeecodes — APPROVED** [review]
Looks right.

**Review by NegativeKB — CHANGES_REQUESTED** [review]
I'd prefer is the package be under "util". Something such as "games.negative.framework.util.proxy" or something like that.

**Comment by NegativeKB** [comment]
Other than that I don't see any other issues.

**Comment by IoyoCode** [comment]
alright, I've moved the class

**Review by NegativeKB — APPROVED** [review]

**Comment by joeecodes** [comment]
oop didnt mean to req review again lol

**Pull request merged**
