### PR TITLE
[FEATURE] Command Cooldowns

### PR DESCRIPTION
**Pull request by seailz**
[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette

 

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

 

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code)
- [x] Documentation
- [ ] Other: \_____ 

 

Closes Issue: #79 

## Description

Added command cooldowns
I'd appreciate reviews for this even if it's not going to be merged until 3.0, so then when 3.0 rolls around, it's ready.

## Documentation
To use command cooldowns, in your constructor for your command, you need to use the `setCooldown` method
Here's an example
```java
setCooldown(sender -> {
    if (sender.getName().equals("seailz"))
       return 40;
    return 0;
});
```
This code means that if the sender's name is `seailz`, their cooldown will be 2 seconds (40 ticks), and if not, their cooldown will be nothing. You can find a tick calculator here: https://mapmaking.fr/tick/ (1 sec = 20 ticks)

### CODE REVIEW

**Comment by joeecodes** [comment]
This won't be merged but we can still review.

**Comment by NegativeDev** [comment]
I'll be doing this feature myself. Also, I'm not a fan of how this entire thing is implemented

**Comment by joeecodes** [comment]
Closed as not currently planned or indev

**Comment by seailz** [comment]
bruh moment

**Pull request closed without merging**
