### PR TITLE
Custom HasteBin

### PR DESCRIPTION
**Pull request by IoyoCode**
[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette 

 
- [x] I have checked the PRs for upcoming features/bug fixes. 
- [x] I have read the [contributing guidelines][contributing]. 

 
### Changes 
- [ ] Internal code 
- [x] Library interface (affecting end-user code) 
- [ ] Documentation 
- [ ] Other: \_____  

 

Closes Issue: https://github.com/Negative-Games/Framework/issues/90

## Description 
Adds the ability for a custom HasteBin URL!

### CODE REVIEW

**Comment by IoyoCode** [comment]
Not sure what base branch to make this - please let me know.

**Comment by IoyoCode** [comment]
I assume it's this branch?

**Review by NegativeDev — APPROVED** [review]

**Comment by NegativeDev** [comment]
Please test and ensure this works

**Comment by IoyoCode** [comment]
Sure

**Comment by IoyoCode** [comment]
Hmm, is there a reason for this error?
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:652)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:154)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1279)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1188)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
	at com.seailz.util.HasteBin.post(HasteBin.java:56)
	at com.seailz.Test.main(Test.java:13)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:128)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:636)
	... 18 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 24 more
Exception in thread "main" java.lang.NullPointerException
	at com.seailz.util.HasteBin.post(HasteBin.java:66)
	at com.seailz.Test.main(Test.java:13)```

**Comment by IoyoCode** [comment]
> Hmm, is there a reason for this error?
> 
> ```
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
> 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:652)
> 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)
> 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)
> 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376)
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
> 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:154)
> 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1279)
> 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1188)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
> 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
> 	at com.seailz.util.HasteBin.post(HasteBin.java:56)
> 	at com.seailz.Test.main(Test.java:13)
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
> 	at sun.security.validator.Validator.validate(Validator.java:271)
> 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:312)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:128)
> 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:636)
> 	... 18 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
> 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
> 	... 24 more
> Exception in thread "main" java.lang.NullPointerException
> 	at com.seailz.util.HasteBin.post(HasteBin.java:66)
> 	at com.seailz.Test.main(Test.java:13)```
> ```

I'm assuming this is a problem with my server - as it works when I input joee's website.

**Pull request merged**
