### PR TITLE
B-Stats / Metrics Tracking

### PR DESCRIPTION
**Pull request by joeecodes**
[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette 

 
- [ ] I have checked the PRs for upcoming features/bug fixes. 
- [ ] I have read the [contributing guidelines][contributing]. 

 
### Changes 
- [ ] Internal code 
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation 
- [ ] Other: \_____  

 

Closes Issue: NaN 

## Description 
Adds a feature to allow us to track Framework usage && let others include bstats in their work

### CODE REVIEW

**Comment by seailz** [comment]
big poggers

**Comment by NegativeDev** [comment]
I don't like to track statistics without the explicit permission(s) from the developers using it / server owners using the plugin

**Comment by joeecodes** [comment]
> I don't like to track statistics without the explicit permission(s) from the developers using it / server owners using the plugin

https://i.imgur.com/sLynVGy.png
It's already a feature

**Comment by joeecodes** [comment]
Could also add a method to disable it

**Comment by NegativeDev** [comment]
> > I don't like to track statistics without the explicit permission(s) from the developers using it / server owners using the plugin
> 
> https://i.imgur.com/sLynVGy.png
> It's already a feature

I'd like it to be am opt-in instead of doing extra stuff to opt out

**Pull request merged**
