### PR TITLE
Confirmation Menu

### PR DESCRIPTION
**Pull request by seailz**
[contributing]: https://github.com/Negative-Games/Framework/blob/main/CONTRIBUTING.md

## Pull Request Etiquette

 

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

 

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code)
- [ ] Documentation
- [ ] Other: \_____ 

 

Closes Issue: NaN

## Description

Allows the end user to quickly create a confirmation menu, to verify whatever they want.

### CODE REVIEW

**Comment by joeecodes** [comment]
Couldn't this just be done with multiple GUIs or replacing the contents of a current GUI, watch if they select the confirmatory button to continue the logic?

**Comment by seailz** [comment]
> Couldn't this just be done with multiple GUIs or replacing the contents of a current GUI

Yes, but it just makes it quicker than making your own confirm GUI?

**Comment by joeecodes** [comment]
> > Couldn't this just be done with multiple GUIs or replacing the contents of a current GUI
> 
> Yes, but it just makes it quicker than making your own confirm GUI?

But is this universally needed? I don't see a reason to add this when it can be achieved without the use of this new thing - this new module already uses things part of the Framework. We add things to make the basic spigot API easier, if we're just adding things that are already a thing (i.e [GUI](https://github.com/Negative-Games/Framework/blob/main/src/main/java/games/negative/framework/gui/GUI.java)).

**Comment by joeecodes** [comment]
Also, this current implementation wouldn't work cross-version.

**Comment by seailz** [comment]
> > > Couldn't this just be done with multiple GUIs or replacing the contents of a current GUI
> 
> > 
> 
> > Yes, but it just makes it quicker than making your own confirm GUI?
> 
> 
> 
> But is this universally needed? I don't see a reason to add this when it can be achieved without the use of this new thing - this new module already uses things part of the Framework. We add things to make the basic spigot API easier, if we're just adding things that are already a thing (i.e [GUI](https://github.com/Negative-Games/Framework/blob/main/src/main/java/games/negative/framework/gui/GUI.java)), then aren't we just adding unnecessary things? We're pretty much reimplementing things that are already added.

that's fair ig, im kinda bored ngl

**Pull request closed without merging**
